# Generated by Django 5.2 on 2025-04-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brawlers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "starPowers",
                    models.CharField(max_length=100, verbose_name="Star Powers"),
                ),
                ("gadgets", models.CharField(max_length=100, verbose_name="Gadgets")),
                (
                    "raridade",
                    models.CharField(
                        choices=[
                            ("RR", "Raro"),
                            ("SR", "Super Raro"),
                            ("EP", "Épico"),
                            ("MT", "Mítico"),
                            ("LD", "Lendario"),
                        ],
                        max_length=2,
                        verbose_name="Raridade",
                    ),
                ),
            ],
        ),
    ]
