# Generated by Django 5.2 on 2025-06-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('artista', models.CharField(max_length=100, verbose_name='Artista')),
                ('album', models.CharField(max_length=100, verbose_name='Album')),
                ('genero', models.CharField(choices=[('POP', 'POP'), ('JPOP', 'J-POP'), ('RCK', 'ROCK'), ('JRCK', 'J-ROCK'), ('MTL', 'METAL'), ('JMTL', 'J-METAL'), ('MPB', 'Musica Popular Brasileira')], max_length=100, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
    ]
