# Generated by Django 5.2 on 2025-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_musicas_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicas',
            name='genero',
            field=models.CharField(choices=[('POP', 'POP'), ('JPOP', 'J-POP'), ('RCK', 'ROCK'), ('JRCK', 'J-ROCK'), ('MTL', 'METAL'), ('JMTL', 'J-METAL'), ('RAP', 'RAP'), ('JRAP', 'J-RAP'), ('CLSC', 'Classica'), ('MPB', 'Musica Popular Brasileira')], max_length=100, verbose_name='Genero'),
        ),
    ]
