# Generated by Django 5.2 on 2025-04-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBrawlers", "0003_alter_brawlers_options_alter_brawlers_raridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brawlers",
            name="gadgets",
            field=models.CharField(max_length=100, verbose_name="Gadget"),
        ),
        migrations.AlterField(
            model_name="brawlers",
            name="starPowers",
            field=models.CharField(max_length=100, verbose_name="Star Power"),
        ),
    ]
