# Generated by Django 5.2 on 2025-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBrawlers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brawlers",
            name="raridade",
            field=models.CharField(
                max_length=100, verbose_name="Raridade, choices=RARIDADE_CHOICES"
            ),
        ),
    ]
