# Generated by Django 5.2 on 2025-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBrawlers", "0002_alter_brawlers_raridade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brawlers",
            options={"verbose_name": "Brawler", "verbose_name_plural": "Brawlers"},
        ),
        migrations.AlterField(
            model_name="brawlers",
            name="raridade",
            field=models.CharField(
                choices=[
                    ("RR", "Raro"),
                    ("SR", "Super Raro"),
                    ("EP", "Épico"),
                    ("MT", "Mítico"),
                    ("LD", "Lendario"),
                ],
                max_length=100,
                verbose_name="Raridade",
            ),
        ),
    ]
